# Dependencies
markdown:         kramdown
highlighter:      rouge
remote_theme:     fongandrew/hydeout

# Setup
title:            CSE 340 Notes
tagline:          ''
description:      '<a href="https://github.com/JetPlaneJJ/CSE340-Notes-MasterList" target="_blank">A Compilation of Notes</a> for <a href="https://courses.cs.washington.edu/courses/cse340/" target="_blank">Interaction Programming</a>.'
url:              https://github.com/JetPlaneJJ
# baseurl:          'cse340wi-notes'

author:
  name:           'Jay Lin'
  url:            https://github.com/JetPlaneJJ

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true

disqus: 
  shortname: jays-cse-340-notes
